os: linux
sudo: required
dist: xenial

before_install:
  - wget https://releases.hashicorp.com/vagrant/2.2.3/vagrant_2.2.3_x86_64.deb
  - sudo dpkg -i vagrant_2.2.3_x86_64.deb
  - sudo apt-get update -qq
  - sudo apt-get install -y -f linux-headers-$(uname -r) virtualbox

install:
  - echo 'SyncedFolders = ["/"]' > local_config.rb

script: bash test.sh
